/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.dynamicCreative;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.hyq0719.mktapi.common.bean.IBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/** 微信视频号信息 */
@ApiModel(description = "微信视频号信息")
public class AdCreativeWechatChannelsSpec implements IBean {
  @SerializedName("export_id")
  private String exportId = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("live_promoted_type")
  private String  livePromotedType = null;

  public AdCreativeWechatChannelsSpec exportId(String exportId) {
    this.exportId = exportId;
    return this;
  }

  /**
   * Get exportId
   *
   * @return exportId
   */
  @ApiModelProperty(value = "")
  public String getExportId() {
    return exportId;
  }

  public void setExportId(String exportId) {
    this.exportId = exportId;
  }

  public AdCreativeWechatChannelsSpec username(String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   *
   * @return username
   */
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public AdCreativeWechatChannelsSpec livePromotedType(String livePromotedType) {
    this.livePromotedType = livePromotedType;
    return this;
  }

  /**
   * Get livePromotedType
   *
   * @return livePromotedType
   */
  @ApiModelProperty(value = "")
  public String getLivePromotedType() {
    return livePromotedType;
  }

  public void setLivePromotedType(String livePromotedType) {
    this.livePromotedType = livePromotedType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdCreativeWechatChannelsSpec adCreativeWechatChannelsSpec = (AdCreativeWechatChannelsSpec) o;
    return Objects.equals(this.exportId, adCreativeWechatChannelsSpec.exportId)
        && Objects.equals(this.username, adCreativeWechatChannelsSpec.username)
        && Objects.equals(this.livePromotedType, adCreativeWechatChannelsSpec.livePromotedType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exportId, username, livePromotedType);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
