/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.dynamicCreative;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.hyq0719.mktapi.common.bean.IBean;
import com.hyq0719.mktapi.tencent.bean.common.AdcreativeMiniProgramSpec;
import com.hyq0719.mktapi.tencent.bean.common.MiniGameSpec;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/** 落地页信息 */
@ApiModel(description = "落地页信息")
public class DynamicCreativePageSpec implements IBean {
  @SerializedName("page_id")
  private Long pageId = null;

  @SerializedName("page_url")
  private String pageUrl = null;

  @SerializedName("mini_program_spec")
  private AdcreativeMiniProgramSpec miniProgramSpec = null;

  @SerializedName("mini_game_spec")
  private MiniGameSpec miniGameSpec = null;

  public DynamicCreativePageSpec pageId(Long pageId) {
    this.pageId = pageId;
    return this;
  }

  /**
   * Get pageId
   *
   * @return pageId
   */
  @ApiModelProperty(value = "")
  public Long getPageId() {
    return pageId;
  }

  public void setPageId(Long pageId) {
    this.pageId = pageId;
  }

  public DynamicCreativePageSpec pageUrl(String pageUrl) {
    this.pageUrl = pageUrl;
    return this;
  }

  /**
   * Get pageUrl
   *
   * @return pageUrl
   */
  @ApiModelProperty(value = "")
  public String getPageUrl() {
    return pageUrl;
  }

  public void setPageUrl(String pageUrl) {
    this.pageUrl = pageUrl;
  }

  public AdcreativeMiniProgramSpec getMiniProgramSpec() {
    return miniProgramSpec;
  }

  public void setMiniProgramSpec(AdcreativeMiniProgramSpec miniProgramSpec) {
    this.miniProgramSpec = miniProgramSpec;
  }

  public MiniGameSpec getMiniGameSpec() {
    return miniGameSpec;
  }

  public void setMiniGameSpec(MiniGameSpec miniGameSpec) {
    this.miniGameSpec = miniGameSpec;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DynamicCreativePageSpec dynamicCreativePageSpec = (DynamicCreativePageSpec) o;
    return Objects.equals(this.pageId, dynamicCreativePageSpec.pageId)
        && Objects.equals(this.pageUrl, dynamicCreativePageSpec.pageUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageId, pageUrl);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
