/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hyq0719.mktapi.tencent.bean.dynamicCreative;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.hyq0719.mktapi.common.bean.IBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/** 动态创意（升级版）信息 */
@ApiModel(description = "动态创意（升级版）信息")
public class ProgramCreativeInfo implements IBean {
  @SerializedName("material_derive_id")
  private Long materialDeriveId = null;

  @SerializedName("bid_mode")
  private String bidMode = null;

  public ProgramCreativeInfo materialDeriveId(Long materialDeriveId) {
    this.materialDeriveId = materialDeriveId;
    return this;
  }

  /**
   * Get materialDeriveId
   *
   * @return materialDeriveId
   */
  @ApiModelProperty(value = "")
  public Long getMaterialDeriveId() {
    return materialDeriveId;
  }

  public void setMaterialDeriveId(Long materialDeriveId) {
    this.materialDeriveId = materialDeriveId;
  }

  public ProgramCreativeInfo bidMode(String bidMode) {
    this.bidMode = bidMode;
    return this;
  }

  /**
   * Get bidMode
   *
   * @return bidMode
   */
  @ApiModelProperty(value = "")
  public String getBidMode() {
    return bidMode;
  }

  public void setBidMode(String bidMode) {
    this.bidMode = bidMode;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProgramCreativeInfo programCreativeInfo = (ProgramCreativeInfo) o;
    return Objects.equals(this.materialDeriveId, programCreativeInfo.materialDeriveId)
        && Objects.equals(this.bidMode, programCreativeInfo.bidMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(materialDeriveId, bidMode);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
